name: Security Checks
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Building Docker Image
         run: docker-compose build
       - name: Launching the app
         run: docker-compose up --detach

       - name: ZAP Full Scan
         uses: zaproxy/action-full-scan@v0.10.0
         with:
              target: 'http://ngage_accounts_service:9095'
              issue_title: 'Security Issues'
              fail_action: false
