name: Full Scan

on:
  push:
    branches:
      - main

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install TruffleHog3
        run: |
          python -m pip install --upgrade pip
          pip install trufflehog3
          
      - name: Run TruffleHog3
        run: |
          trufflehog3 --no-entropy --format json . | jq > truffle_output.json
          
      - name: Upload TruffleHog3 scan results
        uses: actions/upload-artifact@v4
        with:
          name: truffle_output.json
          path: truffle_output.json
          
  semgrep-scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          semgrep \
            --json --output report-semgrep.json \
            --metrics=off \
            --config="p/default"
            
      - name: Upload Semgrep scan results
        uses: actions/upload-artifact@v4
        with:
          name: report-semgrep.json
          path: report-semgrep.json
          
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and start application
        run: |
          docker-compose -f docker-compose.yml up --build --detach

      - name: Run ZAP Full Scan
        run: |
          docker run --network container:$(docker-compose ps -q web) -v $(pwd):/zap/wrk --user root -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
          -t http://web:4000 -I -x /zap/wrk/zap_xml.xml
          
      - name: Upload ZAP scan results
        uses: actions/upload-artifact@v4
        with:
          name: zap_xml_report
          path: zap_xml.xml
