name: DAST Scans

on: [push]

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create Docker network
        run: docker network create zap-network

      - name: Build and start application
        run: |
          docker-compose build
          docker-compose up --detach
          # Optionally wait for the application to be ready
          until curl -s http://localhost:4000 > /dev/null; do
            echo "Waiting for application to be ready..."
            sleep 5
          done

      - name: Run MongoDB container
        run: docker run -d --network zap-network --name mongo mongo:4.4

      - name: ZAP Full Scan
        run: |
          docker run --network zap-network -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
          -t http://localhost:4000 -x zap_xml.xml

      - name: Cleanup
        run: |
          docker-compose down
          docker network rm zap-network
