name: ZAP Full Scan

on: [push]

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and start application
        run: |
          docker-compose -f docker-compose.yml up --build --detach
          # Optionally wait for the application to be ready
          until curl -s http://localhost:4000 > /dev/null; do
            echo "Waiting for application to be ready..."
            sleep 5
          done

      - name: Prepare ZAP directories
        run: |
          docker run --rm -v $(pwd):/zap ghcr.io/zaproxy/zaproxy:stable \
          sh -c "mkdir -p /zap/wrk && chmod 777 /zap/wrk"

      - name: ZAP Full Scan
        run: |
          docker run --network container:$(docker-compose ps -q web) -v $(pwd):/zap/wrk -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
          -t http://web:4000 -x /zap/wrk/zap_xml.xml

      - name: Cleanup
        run: docker-compose down
